interclip/interclip

includes/api.php, includes/components/get.php, includes/get-api.php
JSON rocks, plain text goes!
Fixes #31
=> API to return JSON

css/dark.css, css/index.css, js/file.js
Make the dropping much more responsive and user friendly.
=> Drop responsiveness

includes/get.php, includes/new.php
=> Upgrade to newest embed lib update

css/index.css, js/index.js
=> Input bubble update

.gitignore, composer.json, composer.lock, includes/components/rate.php, includes/components/short-api.php, phpunit.xml, tests/Pest.php
Create a couple of tests with Pest.
=> Add simple tests

composer.json, composer.lock, includes/components/new.php, includes/verify-domain.php
Use [io-developer/php-whois](https://github.com/io-developer/php-whois) to see if a domain is valid and if not, it should make the API not result in success.
=> Domain checking

includes/api.php, includes/components/new.php, includes/components/outputs/new-ok-msg.php, includes/components/rate.php
=> Make them errors looks awesome again

includes/get.php, includes/new.php
Some code rewrites, easy peasy.
=> Rewrite ifs

about.php, js/about.js
=> Auto release from git

.gitpod.yml, includes/components/outputs/new-ok-msg.php
=> Fix QR code colors

LEGAL.md, about.php
This pull request makes the about page a lot cleaner with no screenshots or junk like that.
=> New about page

includes/get.php
=> Manage null code

css/dark.css, css/menu.css, css/recieve.css, includes/menu.php, js/menu.js, js/recieve.js
Fixes #76 
Design mockup: https://codepen.io/filip_tronicek/pen/qBRdGPz?editors=0101
=> Settings modal

about.php, desktop.php, includes/components/file-ok.php, includes/get.php, includes/new.php, recieve.php
Some files include jQuery for a second time, since it's already included in the menu, making it not very poggers.
=> Remove jQuery from some places

includes/anti-csrf.php, includes/get.php, includes/new.php, index.php, recieve.php
Fixes #89 so bad guys don't... clip something on your behalf? Well, anyway, just good practice to have 'em.
=> Anti-CSRF tokens

.env.sample, .gitignore, about.php, composer.json, composer.lock, desktop.php, file.php, includes/components/get.php, includes/components/new.php, includes/components/rate.php, includes/error.php, includes/get.php, includes/menu.php, includes/new.php, index.php, privacy.php, r.php, recieve.php, scripts/.gitpod.env, scripts/secrets.sh
=> Implement .env

api/facts.js, css/dark.css, css/file.css, css/progressbar.css, file.php, includes/components/file-ok.php, index.php, js/file.js
Add a file upload progress bar
Todo:
=> Progress bar

about.php, desktop.php, file.php, includes/get.php, includes/header.php, includes/menu.php, includes/new.php, index.php, privacy.php, receive.php
Move the header of all pages a separate file for less code duplication and more consistency.
=> Create a header file and include it everywhere

.env.sample, css/menu.css, includes/change-branch.php, includes/components/html/meta-tags.php, includes/header.php, includes/lib/auth.php, includes/lib/headers.php, includes/lib/init.php, includes/lib/sentry.php, includes/menu.php, js/menu.js, scripts/.gitpod.env
This admin bar will be able to change branches among other things to preview them before they go into production
=> feat: Create a staging admin bar

css/new.css, includes/components/html/new/ok-msg.php, includes/new.php
=> perf: Solve QR codes once and for all

admin/index.php, css/admin.css, includes/components/html/adminbar.php, includes/lib/functions.php, js/admin.js, js/menu.js, upload/index.php
Create a `/admin/` admin dashboard, which can be used to monitor many metrics all over Interclip.
=> feat: Admin page

.gitpod.yml, CONTRIBUTING.md, includes/components/get.php, includes/components/new.php, includes/components/redis.php, public/receive.php, scss/receive.scss
Add Redis to drastically speed up newer clips. (citation needed)
Fixes #142
=> feat: Redis

composer.json, tests/Pest.php, tests/Unit/LibraryFunctionsTest.php
Update `pestphp/pest` dev requirement to a newer version and clean up the tests to use higher-order tests. 👍
=> Update test suite

includes/components/get.php, includes/components/new.php
This PR updates the queries for clips to use prepared statements, this protects against SQL injection attacks.
=> Update db queries to use prepared statements

js/file.js, js/menu.js, public/index.php, scss/dark.scss, scss/file.scss, scss/index.scss, scss/menu.scss
Added a new drag and drop interface for files
=> New drag n' drop

.gitpod.yml, composer.json, composer.lock, includes/components/html/adminbar.php, includes/lib/auth.php, public/login.php
=> Update auth0 to v8

includes/verify-domain.php
=> Exclude onion sites from domain validation
